'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var LATEST_TOPIC_LIST = exports.LATEST_TOPIC_LIST = 'LATEST_TOPIC_LIST';

var TOPIC_DETAIL_DATA = exports.TOPIC_DETAIL_DATA = 'TOPIC_DETAIL_DATA';

var TOPIC_REPLIES_DATA = exports.TOPIC_REPLIES_DATA = 'TOPIC_REPLIES_DATA';

var HOT_TOPIC_DATA = exports.HOT_TOPIC_DATA = 'HOT_TOPIC_DATA';

var NODE_INFO_DATA = exports.NODE_INFO_DATA = 'NODE_INFO_DATA';

var MEMBER_INFO_DATA = exports.MEMBER_INFO_DATA = 'MEMBER_INFO_DATA';